name: Nuxt Cloud Deployment

on:
  release:
    types: [published]

jobs:
  test:
    uses: $/.github/workflows/lint_and_test.yml
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push release into hosting via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secreats.PASSPHRASE }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          script: |
            cd /var/www/schedule-bot || (git clone git@github.com:mega-daun/schedule-bot.git /var/www/schedule-bot && cd /var/www/schedule-bot)
            git pull origin main
            composer install --no-dev
